export const els = {
  letters: document.getElementById("letters") as HTMLElement,
  input: document.getElementById("typing-input") as HTMLInputElement,
  healthBar: document.getElementById("health-bar") as HTMLElement,
  healthText: document.getElementById("health-text") as HTMLElement,
  score: document.getElementById("score") as HTMLElement,
  time: document.getElementById("time") as HTMLElement,
  threat: document.getElementById("threat-level") as HTMLElement,
  lobbyScreen: document.getElementById("lobby-screen") as HTMLElement,
  gameOverScreen: document.getElementById("game-over-screen") as HTMLElement,
  endScreenTitle: document.getElementById("end-screen-title") as HTMLElement,
  lobbyPlayerList: document.getElementById("lobby-player-list") as HTMLElement,
  lobbyCodeDisplay: document.getElementById("lobby-code-display") as HTMLElement,
  multiplayerSidebar: document.getElementById("multiplayer-sidebar") as HTMLElement,
  creatorControls: document.getElementById("creator-controls") as HTMLElement,
  finalStats: document.getElementById("final-stats") as HTMLElement,
  createBtn: document.getElementById("create-btn") as HTMLButtonElement,
  joinBtn: document.getElementById("join-btn") as HTMLButtonElement,
  startBtn: document.getElementById("start-btn") as HTMLButtonElement,
  leaveBtn: document.getElementById("leave-btn") as HTMLButtonElement,
  leaveAfterGameBtn: document.getElementById("leave-after-game-btn") as HTMLButtonElement,
  leaveInGameBtn: document.getElementById("leave-in-game-btn") as HTMLButtonElement,
  usernameInput: document.getElementById("username-input") as HTMLInputElement,
  roomCodeInput: document.getElementById("join-code-input") as HTMLInputElement,
  particles: document.getElementById("particles") as HTMLElement,
  rulesBtn: document.getElementById("rules-btn") as HTMLButtonElement | null,
  rulesScreen: document.getElementById("rules-screen") as HTMLElement | null,
  rulesCloseBtn: document.getElementById("rules-close-btn") as HTMLButtonElement | null,
  rulesContent: document.getElementById("rules-content") as HTMLElement | null,
};

